name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Bun
        if: steps.config.outputs.skip-platform != 'true'
        uses: oven-sh/setup-bun@v2
      - name: Setup Node.js
        if: steps.config.outputs.skip-platform != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Build
        run: bun run build
      - name: Run ESLint
        run: bun lint --fix=false
      - name: Run Biome
        run: bun biome ci .
