name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Use Node.js v22
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version: 22
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Build
        run: yarn build
      - name: Run ESLint
        run: yarn lint --fix=false
      - name: Run Biome
        run: yarn biome ci .
